### ISSUE TITLE
[Bug] GUI not separating different contacts in the schedule

### ISSUE THREAD

**Issue by QuekBingHeng** [AY2425S1-CS2103-F13-3/tp#133]
**Issue**

Different contacts are not separated and are joined together in the schedule as shown:

![image](https://github.com/user-attachments/assets/5cc02ab4-2911-4e90-87b4-507db4c7fe3e)

**Comment by LimKaiWei** [comment]
@jewiteo do you think `VBox` or `ListView` might be better than `flowpane`?
