### ISSUE TITLE
[PE-D][Tester C] Allow 2 same person to be in the same meeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-3/tp#185]
Might be better to flag out that 2 same person have been added to the same meeting.

![error 2.png](https://raw.githubusercontent.com/Tanziyanghenry/ped/main/files/d5babef1-639b-4d5e-b660-11445a65f50d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Tanziyanghenry/ped#3

**Comment by QuekBingHeng** [comment]
Will fix this bug so that future add-schedule commands will not be able to have duplicate indices.
