### ISSUE TITLE
[PE-D][Tester E] User is not allowed to create schedules with no contacts but such schedules exist after deleting the contacts that were originally in those

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-3/tp#211]
The user is not permitted to create schedules without contacts. However, if the contacts for a meeting are deleted, the meeting will appear contact-less after a refresh (due to the schedule UI not updating immediately, which is another bug). This scenario, where a meeting has no associated contact, should not be allowed.

![Screenshot 2024-11-08 at 4.59.07 PM.png](https://raw.githubusercontent.com/limyuquan/ped/main/files/25dc16e1-86f3-4a49-99cf-cd7dc6d3a5bf.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: limyuquan/ped#11

**Comment by LimKaiWei** [comment]
Issue unclear on how to replicate. Possibly addresses in DG planned enhacements under point 1 or 2 already. closing this issue.
