### ISSUE TITLE
[PE-D][Tester E] No error feedback when nothing is keyed in the command input but User enters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-3/tp#215]
When nothing is keyed in the command input and the user enters, there is no feedback to the user. The application should prompt for input or display an error message.

![Screenshot 2024-11-08 at 5.05.06 PM.png](https://raw.githubusercontent.com/limyuquan/ped/main/files/fccce18e-8fd7-4528-9927-b66859b083f8.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: limyuquan/ped#13

**Comment by jewiteo** [comment]
I think intuitively the expected behaviour is for nothing to show instead of having an error message. A similar case would be Googling or searching for websites, where pressing enter on empty inputs no error message or prompts are shown.
