### ISSUE TITLE
[PE-D][Tester B] FeatureFlaw: Favourite should be grouped at the top

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-3/tp#254]
Favouriting a person is a good idea, but it simply adds a star on the top right without any other extra function. One suggestion would be to group the favourites at the top which allows the user to quickly access them and add them to meetings efficiently and quickly.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RadieonAjax/ped#18

**Comment by tata32000** [comment]
This is considered as enhancement
